name: Publish Package to npmjs

on:
  release:
    types: [published]
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          release-as: 0.0.11
          package-name: release-please-action
          last-release-sha: '2a5c3fb1ae521d40c453cd0f6282970cdedcc100'
